import { ButtonLink } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Plus } from 'lucide-react'

const APP_URL = 'https://app.altacpe.com'

export const metadata = { title: 'Contact | Alta Professional Accreditation', description: 'Contact Alta Professional Accreditation for provider approval and CPE accreditation guidance.' }

const officeRegions = [
  { name: 'North America', offices: [['New York, USA', '165 Broadway, 23rd Floor, New York, NY 10006, USA'], ['Toronto, Canada', '130 King Street West, Exchange Tower, Suite 1900, Toronto, ON M5X 1E3, Canada']] },
  { name: 'Europe', offices: [['London, UK', '48 Warwick Street, London W1B 5AW, United Kingdom'], ['Paris, France', '10 Place Vendôme, 75001 Paris, France'], ['Amsterdam, Netherlands', 'Herengracht 280, 1016 BX Amsterdam, Netherlands']] },
  { name: 'Middle East', offices: [['Dubai, UAE', 'Boulevard Plaza, Tower 1, Level 9, Sheikh Mohammed Bin Rashid Boulevard, Dubai, United Arab Emirates']] },
  { name: 'Africa', offices: [['Johannesburg, South Africa', 'Atrium on 5th, 9th Floor, 5th Street, Sandton, Johannesburg, 2196, South Africa'], ['Cape Town, South Africa', '50 Long Street, Cape Town, 8000, South Africa'], ['Nairobi, Kenya', 'I&M Tower, 15th–17th Floors, Kenyatta Avenue, Nairobi, 00100, Kenya'], ['Lagos, Nigeria', '927/928 Bishop Aboyade Cole Street, Mansard Place, 3rd Floor, Victoria Island, Lagos, 106104, Nigeria'], ['Casablanca, Morocco', 'Crystal Building 1, 10th Floor, Almohades Avenue, Casablanca, 20000, Morocco'], ['Cairo, Egypt', 'Nile City Towers, North Tower, 19th Floor, Corniche El Nile, Cairo, Egypt']] },
  { name: 'Asia-Pacific', offices: [['Singapore', '12 Marina Boulevard, #17-01, Marina Bay Financial Centre Tower 3, Singapore 018982'], ['Tokyo, Japan', 'Pacific Century Place Marunouchi, Level 13, 1-11-1 Marunouchi, Chiyoda-ku, Tokyo 100-6213, Japan'], ['Sydney, Australia', '20 Martin Place, Levels 10 & 11, Sydney, NSW 2000, Australia'], ['Auckland, New Zealand', '11–19 Customs Street West, Commercial Bay Tower, Level 17, Auckland, 1010, New Zealand'], ['Hong Kong', 'The Centre, 66th Floor, 99 Queen’s Road Central, Hong Kong']] },
]

export default function ContactPage() {
  return <main className="contact-page">
    <section className="contact-hero"><div className="contact-hero-copy"><nav className="contact-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">Contact</span></nav><p className="eyebrow">Contact Alta Professional Accreditation</p><h1>Start a clearer accreditation conversation.</h1><p className="lead">Tell us about your professional learning offer, your priority programmes and the confidence you want to build with learners and partners.</p><ButtonLink href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div><figure className="contact-hero-image"><Image src="/images/page-contact.png" alt="Two professionals having a consultation" fill priority sizes="(max-width: 700px) 100vw, 100vw" /></figure></section>
    <section className="contact-intro section-wrap"><figure><Image src="/images/detail-contact.png" alt="Professionals discussing professional learning" fill sizes="(max-width: 700px) 100vw, 44vw" /></figure><div><p className="eyebrow">How we can help</p><h2>Start with the context behind your learning offer.</h2><p>Alta Professional Accreditation can help you understand the most useful route for your organisation, whether you are exploring provider approval or preparing priority courses for accreditation.</p><p>Share the programmes you deliver, the professionals you support and the quality practices already in place. A clear overview creates a more focused next step.</p></div></section>
    <section className="contact-questions section-wrap"><div><p className="eyebrow">Contact FAQs</p><h2>Helpful answers before you write.</h2></div><div className="contact-faq-list"><details><summary>Should we use email or free provider approval?<Plus aria-hidden="true" /></summary><p>Use free provider approval to introduce your learning offer and explore an accreditation route. Use email support for a general question or practical clarification.</p></details><details><summary>What should we include in an enquiry?<Plus aria-hidden="true" /></summary><p>Include your organisation, the professional learning you provide, the audiences you support and the outcome you are working towards.</p></details><details><summary>Can we ask about a specific course?<Plus aria-hidden="true" /></summary><p>Yes. Tell us about the programme, its intended learners, outcomes and the evidence you already have available.</p></details><details><summary>Do we need to visit an office?<Plus aria-hidden="true" /></summary><p>No. You can start the conversation through free provider approval or email support.</p></details></div></section>
    <section className="contact-cta"><div className="section-wrap"><div><p className="eyebrow">Ready when you are</p><h2>Start with free provider approval.</h2><p>Tell Alta Professional Accreditation about your CPE offer and identify the route that fits your organisation.</p></div><ButtonLink variant="secondary" href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div></section>
    <section className="office-directory"><div className="section-wrap"><p className="eyebrow">Appointment-only meeting locations</p><h2>Global offices for scheduled meetings.</h2><p>Email <a href="mailto:hello@altacpe.com">hello@altacpe.com</a> to arrange an appointment.</p><div className="office-regions">{officeRegions.map(({ name, offices }) => <section key={name}><h3>{name}</h3><ul>{offices.map(([city, address]) => <li key={address}><strong>{city}</strong><span>{address}</span></li>)}</ul></section>)}</div></div></section>
  </main>
}
