import { ButtonLink } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'

const APP_URL = 'https://app.altacpe.com'
export const metadata = { title: 'Assessment Standards | Alta Professional Accreditation', description: 'Explore the assessment standards used by Alta Professional Accreditation.' }

const standards = [
  ['learning-quality', 'Learning quality', 'Learning begins with a clear professional purpose. Alta Professional Accreditation considers whether outcomes, content, learning design and review practices work together to create useful CPE.', '/images/standards-learning-quality.png'],
  ['governance', 'Provider governance', 'Strong governance makes quality dependable. We look at how accountability, decision making, policies and oversight give a provider the structure to manage its learning offer responsibly.', '/images/standards-governance.png'],
  ['learner-support', 'Learner support', 'Professionals need clear information and practical support before, during and after learning. This area considers the experience providers create around participation, access and communication.', '/images/standards-learner-support.png'],
  ['education-delivery', 'Education delivery', 'Delivery brings a programme to life. Alta Professional Accreditation considers the capability of people, suitability of formats and reliability of the arrangements that learners depend on.', '/images/standards-delivery.png'],
]

export default function StandardsPage() {
  return <main className="standards-page standalone-page">
    <section className="standalone-hero"><div className="standalone-hero-copy"><nav className="standalone-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">Assessment standards</span></nav><p className="eyebrow">Alta Professional Accreditation standards</p><h1>The principles behind credible professional learning.</h1><p className="lead">Our assessment standards help providers show how their continuing professional education is designed, governed, supported and delivered with purpose.</p><ButtonLink href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div><figure><Image src="/images/page-standards.png" alt="Professional education session in progress" fill priority sizes="100vw" /></figure></section>
    <section className="standalone-intro section-wrap"><figure><Image src="/images/detail-standards.png" alt="Professionals planning an education programme" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">A practical frame</p><h2>Standards that help quality become visible.</h2><p>Alta Professional Accreditation uses standards to create a common, understandable view of what sits behind a trustworthy CPE experience. They are designed to focus attention on the practices that learners, employers and partners need providers to get right.</p><p>The standards are not a script for every provider. They give each organisation a way to explain the choices it makes and the evidence that supports them.</p></div></section>
    <section className="standalone-dark"><div className="section-wrap"><p className="eyebrow">The assessment approach</p><h2>Look at the whole provider experience.</h2><div className="statement-grid"><article><span>01</span><h3>Purpose</h3><p>Learning should address real professional needs with defined outcomes.</p></article><article><span>02</span><h3>Practice</h3><p>Providers should show how quality is applied, not simply described.</p></article><article><span>03</span><h3>Evidence</h3><p>Information should give a clear picture of the learning experience.</p></article><article><span>04</span><h3>Improvement</h3><p>Feedback and review should keep provision relevant over time.</p></article></div></div></section>
    <section className="standards-list">{standards.map(([id, title, text, image], index) => <article className="standalone-split section-wrap" id={id} key={id}><div><p className="eyebrow">Assessment area 0{index + 1}</p><h2>{title}</h2><p>{text}</p><p>Providers can use this area to consider the policies, people, programme materials and ways of working that demonstrate their approach to Alta Professional Accreditation.</p></div><figure><Image src={image} alt="Professional learning environment" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure></article>)}</section>
    <section className="standalone-feature section-wrap"><figure><Image src="/images/standards-improvement.png" alt="Team reflecting on professional learning quality" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">Quality over time</p><h2>Use insight to keep learning current.</h2><p>Professional expectations change. Feedback, participation insight and changes in practice help providers identify where programmes should be updated, clarified or strengthened.</p><p>Alta Professional Accreditation values the habits that turn those signals into deliberate improvement across a CPE offer.</p></div></section>
    <section className="standalone-steps section-wrap"><p className="eyebrow">Preparing for assessment</p><h2>Start with the evidence closest to your everyday practice.</h2><ol><li><span>01</span><div><h3>Map your provision</h3><p>Identify the programmes, learners and quality practices that make up your CPE offer.</p></div></li><li><span>02</span><div><h3>Review each area</h3><p>Use the four standards to locate the evidence and context worth presenting.</p></div></li><li><span>03</span><div><h3>Choose your route</h3><p>Start free provider approval with Alta Professional Accreditation.</p></div></li></ol></section>
    <section className="provider-cta standalone-cta"><div className="provider-cta-inner section-wrap"><div><p className="eyebrow">Ready when you are</p><h2>Turn your quality standards into a confident next step.</h2><p>Start free provider approval with a clear view of the CPE practices you want to demonstrate.</p></div><div className="provider-cta-actions"><ul><li><Check aria-hidden="true" />Clear assessment areas</li><li><Check aria-hidden="true" />A practical starting point</li><li><Check aria-hidden="true" />Support for your CPE offer</li></ul><ButtonLink variant="inverse" href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div></div></section>
  </main>
}
