import { ButtonLink } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'

const APP_URL = 'https://app.altacpe.com'
export const metadata = { title: 'About Us | Alta Professional Accreditation', description: 'Learn about Alta Professional Accreditation and our role in continuing professional education.' }

export default function AboutPage() {
  return <main className="about-page standalone-page">
    <section className="standalone-hero"><div className="standalone-hero-copy"><nav className="standalone-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">About us</span></nav><p className="eyebrow">About Alta Professional Accreditation</p><h1>Helping professional learning earn confidence.</h1><p className="lead">Alta Professional Accreditation is a private accreditation body focused on the quality behind continuing professional education.</p><ButtonLink href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div><figure><Image src="/images/page-about.png" alt="Professional learning leaders in conversation" fill priority sizes="100vw" /></figure></section>
    <section className="standalone-intro section-wrap"><figure><Image src="/images/detail-about.png" alt="Professionals discussing education quality" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">Our role</p><h2>Bring greater clarity to professional education.</h2><p>Working professionals make important choices about where to invest their time and attention. Alta Professional Accreditation helps providers demonstrate the quality, structure and care behind those choices.</p><p>Our work focuses on continuing professional education: learning that supports people as their responsibilities, knowledge and professional context develop.</p></div></section>
    <section className="standalone-dark"><div className="section-wrap"><p className="eyebrow">What guides us</p><h2>Confidence comes from the details behind a learning experience.</h2><div className="statement-grid"><article><span>01</span><h3>Professional relevance</h3><p>Learning should connect to current practice and meaningful capability.</p></article><article><span>02</span><h3>Clear expectations</h3><p>Providers and learners should understand what quality looks like.</p></article><article><span>03</span><h3>Responsible provision</h3><p>Education deserves governance, care and accountable decisions.</p></article><article><span>04</span><h3>Ongoing improvement</h3><p>Strong providers listen, learn and keep their offer current.</p></article></div></div></section>
    <section className="standalone-split section-wrap"><div><p className="eyebrow">What we accredit</p><h2>Provider practices and priority programmes.</h2><p>Alta Professional Accreditation works with organisations that deliver structured continuing professional education. Our routes recognise the difference between an organisation-wide quality approach and the needs of a specific course or programme.</p><p>Free provider approval helps organisations begin the right conversation. Pay-per-course accreditation provides a practical route for priority learning offers.</p></div><figure><Image src="/images/professional-learning-hero.png" alt="Professionals participating in continuing education" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure></section>
    <section className="standalone-feature section-wrap"><figure><Image src="/images/standards-governance.png" alt="Leadership team reviewing education governance" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">How we assess</p><h2>A balanced view of the whole learning experience.</h2><p>Alta Professional Accreditation considers learning quality, provider governance, learner support and education delivery. Together, these areas help us understand whether a provider’s offer is planned and managed in a way professionals can trust.</p><ul><li><Check aria-hidden="true" />Relevant learning and intended outcomes</li><li><Check aria-hidden="true" />Clear governance and accountable practice</li><li><Check aria-hidden="true" />Support and reliable programme delivery</li></ul></div></section>
    <section className="standalone-routes"><div className="section-wrap"><div><p className="eyebrow">A global professional context</p><h2>For providers serving professionals wherever they work.</h2></div><div className="route-lines"><article><strong>Professional learning changes quickly</strong><p>Providers respond to new responsibilities, regulation, technology and sector expectations. We help quality remain visible as portfolios evolve.</p></article><article><strong>Recognition should be understandable</strong><p>Alta Professional Accreditation gives providers a clear way to explain the practice behind their offer to learners, employers and partners.</p></article></div></div></section>
    <section className="standalone-steps section-wrap"><p className="eyebrow">Working with Alta Professional Accreditation</p><h2>Start with the learning offer you want to strengthen.</h2><ol><li><span>01</span><div><h3>Tell us your context</h3><p>Introduce your organisation, learners and professional education priorities.</p></div></li><li><span>02</span><div><h3>Explore the right route</h3><p>Choose free provider approval or a focused course accreditation discussion.</p></div></li><li><span>03</span><div><h3>Build a credible submission</h3><p>Show the practices that make your professional learning worthy of confidence.</p></div></li></ol></section>
    <section className="provider-cta standalone-cta"><div className="provider-cta-inner section-wrap"><div><p className="eyebrow">Ready when you are</p><h2>Give professionals a clearer reason to trust your learning.</h2><p>Start free provider approval with Alta Professional Accreditation.</p></div><div className="provider-cta-actions"><ul><li><Check aria-hidden="true" />Free provider approval</li><li><Check aria-hidden="true" />A route for providers or courses</li><li><Check aria-hidden="true" />Credible CPE recognition</li></ul><ButtonLink variant="inverse" href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div></div></section>
  </main>
}
