import { ButtonLink } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'

const APP_URL = 'https://app.altacpe.com'

export const metadata = { title: 'Provider Accreditation | Alta Professional Accreditation', description: 'Explore provider accreditation from Alta Professional Accreditation.' }

export default function AccreditationPage() {
  return <main className="accreditation-page standalone-page">
    <section className="standalone-hero"><div className="standalone-hero-copy"><nav className="standalone-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">Provider accreditation</span></nav><p className="eyebrow">Alta Professional Accreditation</p><h1>Build confidence in your CPE provision.</h1><p className="lead">Provider accreditation gives organisations a credible way to show the care, structure and accountability behind their continuing professional education.</p><ButtonLink href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div><figure><Image src="/images/page-accreditation.png" alt="Professionals reviewing a learning programme" fill priority sizes="100vw" /></figure></section>
    <section className="standalone-intro section-wrap"><figure><Image src="/images/detail-accreditation.png" alt="Learning provider team in discussion" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">A recognised quality signal</p><h2>Make the strength of your learning offer easier to see.</h2><p>Alta Professional Accreditation gives training institutions and education providers a structured accreditation route built around the realities of continuing professional education. It helps you demonstrate how your organisation designs, governs and delivers learning for professionals.</p><p>For learners, employers and partners, accreditation creates a clearer basis for confidence. For your team, it gives the work already happening behind the scenes a purposeful framework.</p></div></section>
    <section className="standalone-dark"><div className="section-wrap"><p className="eyebrow">What accreditation communicates</p><h2>Four parts of a credible provider story.</h2><div className="statement-grid"><article><span>01</span><h3>Learning quality</h3><p>Programmes begin with defined professional needs and outcomes that matter.</p></article><article><span>02</span><h3>Responsible governance</h3><p>Clear ownership and decisions support consistent, accountable practice.</p></article><article><span>03</span><h3>Learner support</h3><p>Professionals have the information and help needed to participate well.</p></article><article><span>04</span><h3>Reliable delivery</h3><p>Courses are delivered with care, capable people and dependable systems.</p></article></div></div></section>
    <section className="standalone-split section-wrap" id="quality"><div><p className="eyebrow">Who it is for</p><h2>For providers that take professional learning seriously.</h2><p>Alta Professional Accreditation is suited to organisations that deliver structured learning for working professionals. You may offer a portfolio across a profession, specialist programmes for a sector, technical education or leadership development.</p><p>What matters is the intention behind the offer: learning should be planned, relevant and supported by practices that help people make informed choices about where to invest their time.</p></div><figure><Image src="/images/provider-accreditation-review.png" alt="Provider team reviewing an accreditation submission" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure></section>
    <section className="standalone-feature section-wrap"><figure><Image src="/images/standards-evidence.png" alt="Professional reviewing programme evidence" fill sizes="(max-width: 700px) 100vw, 45vw" /></figure><div><p className="eyebrow">Your application</p><h2>Present the practices that sit behind your programmes.</h2><p>An Alta Professional Accreditation application is a chance to explain how your learning approach works in practice. Bring together the decisions, materials and evidence that show the quality of your provision.</p><ul><li><Check aria-hidden="true" />Purpose and intended learner outcomes</li><li><Check aria-hidden="true" />Programme design and review practices</li><li><Check aria-hidden="true" />Governance, support and delivery arrangements</li></ul></div></section>
    <section className="standalone-routes"><div className="section-wrap"><div><p className="eyebrow">Choose your route</p><h2>Start with your organisation or a priority course.</h2></div><div className="route-lines"><article><strong>Free provider approval</strong><p>Introduce your organisation and explore the right accreditation route before preparing a full application.</p><ButtonLink href={APP_URL} variant="outline">Start provider approval <ArrowRight aria-hidden="true" /></ButtonLink></article><article><strong>Pay per course accreditation</strong><p>Bring forward a specific programme when course-level recognition is the practical next step for your offer.</p><ButtonLink href={APP_URL} variant="outline">Discuss a course <ArrowRight aria-hidden="true" /></ButtonLink></article></div></div></section>
    <section className="standalone-steps section-wrap"><p className="eyebrow">A considered process</p><h2>Move forward with a clear view of the next step.</h2><ol><li><span>01</span><div><h3>Introduce your provision</h3><p>Share the context, learners and accreditation priority behind your CPE offer.</p></div></li><li><span>02</span><div><h3>Confirm the right route</h3><p>Start with provider approval or focus on a defined course opportunity.</p></div></li><li><span>03</span><div><h3>Prepare your evidence</h3><p>Use the assessment areas to organise a focused, meaningful submission.</p></div></li></ol></section>
    <section className="provider-cta standalone-cta"><div className="provider-cta-inner section-wrap"><div><p className="eyebrow">Ready when you are</p><h2>Make the quality behind your CPE offer visible.</h2><p>Begin with free provider approval and choose the route that suits your organisation.</p></div><div className="provider-cta-actions"><ul><li><Check aria-hidden="true" />Free provider approval</li><li><Check aria-hidden="true" />Clear accreditation routes</li><li><Check aria-hidden="true" />Support for CPE providers</li></ul><ButtonLink variant="inverse" href={APP_URL}>Start free provider approval <ArrowRight aria-hidden="true" /></ButtonLink></div></div></section>
  </main>
}
